// FavoriteCharacters.styled.ts

import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    padding: 16,
    backgroundColor: '#fff',
  },
  emptyText: {
    textAlign: 'center',
    fontSize: 18,
    marginTop: 20,
    color: '#555',
  },
  searchInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#ddd',
    backgroundColor: '#f9f9f9',
    marginBottom: 10,
  },
  searchIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
  },
  searchInput: {
    flex: 1,
    height: '100%',
    fontSize: 14,
    textAlignVertical: 'center',
    padding: 0,
  },
  filterButton: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 8,
    paddingRight: 16,
    paddingBottom: 8,
    paddingLeft: 24,
    backgroundColor: '#224229',
    borderRadius: 22,
    marginBottom: 10,
    width: 113,
  },
  filterButtonActive: {
    backgroundColor: '#162C1B',
  },
  filterButtonInactive: {
    backgroundColor: '#224229',
  },
  filterButtonText: {
    color: '#fff',
    fontSize: 14,
    fontWeight: 'bold',
    flex: 1,
    marginRight: 8,
  },
  arrowIcon: {
    width: 14,
    height: 14,
    transform: [{ rotate: '0deg' }],
  },
  filterSection: {
    backgroundColor: '#FFFFFF',
    padding: 16,
    borderRadius: 12,
    borderColor: '#224229',
    borderWidth: 1,
    shadowColor: '#224229',
    shadowOffset: { width: 4, height: 4 },
    shadowOpacity: 1,
    shadowRadius: 0,
    elevation: 5,
    marginBottom: 10,
  },
  modalLabel: {
    fontFamily: 'DM Mono',
    fontSize: 12,
    fontWeight: '500',
    color: '#59695C',
    letterSpacing: 0.08,
    marginBottom: 8,
  },
  checkboxContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 1,
    borderColor: '#224229',
    borderRadius: 4,
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  checkboxChecked: {
    backgroundColor: '#000000',
  },
  checkboxIcon: {
    width: 12,
    height: 12,
    tintColor: '#FFFFFF',
  },
  checkboxLabel: {
    fontSize: 16,
    color: '#162C1B',
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 24,
  },
  modalButton: {
    width: 74,
    height: 34,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#224229',
    justifyContent: 'center',
    alignItems: 'center',
  },
  resetButton: {
    backgroundColor: '#fff',
  },
  applyButton: {
    backgroundColor: '#224229',
  },
  modalButtonText: {
    fontSize: 14,
    fontWeight: 'bold',
    color: '#162C1B',
  },
  modalButtonText2: {
    fontSize: 14,
    fontWeight: 'bold',
    color: 'white',
  },
  paginationContainer: {
    flexDirection: 'row',
    justifyContent: 'center',
    marginTop: 10,
  },
  paginationButton: {
    marginHorizontal: 5,
    width: 30,
    height: 30,
    borderRadius: 5,
    backgroundColor: '#3D3D49',
    justifyContent: 'center',
    alignItems: 'center',
  },
  paginationButtonActive: {
    backgroundColor: '#FF9F1C',
  },
  paginationText: {
    color: 'white',
    fontSize: 14,
  },
  paginationTextActive: {
    color: '#000',
    fontWeight: 'bold',
  },
  // Card Styles
  cardWrapper: {
    position: 'relative',
    marginVertical: 10,
    paddingBottom: 4,
    paddingRight: 4,
    backgroundColor: '#224229',
    borderRadius: 24,
  },
  card: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    padding: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#224229',
    borderRadius: 24,
    margin: 0,
  },
  imageContainer: {
    position: 'relative',
  },
  cardImage: {
    width: 200,
    height: 200,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#224229',
  },
  cardContent: {
    flex: 1,
    justifyContent: 'center',
  },
  infoBlock: {
    padding: 8,
    gap: 4,
  },
  label: {
    fontFamily: 'DM Mono',
    fontSize: 12,
    fontWeight: '500',
    lineHeight: 15.62,
    letterSpacing: 0.08,
    textAlign: 'left',
    color: '#59695C',
  },
  bodyText: {
    fontFamily: 'Inter',
    fontSize: 16,
    fontWeight: '400',
    lineHeight: 19.36,
    letterSpacing: -0.02,
    textAlign: 'left',
    color: '#162C1B',
  },
  likeButton: {
    position: 'absolute',
    bottom: 10,
    right: 10,
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    backgroundColor: '#FFFFFF',
    borderRadius: 100,
    borderWidth: 1,
    borderColor: '#224229',
    shadowColor: '#224229',
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.8,
    shadowRadius: 4,
    elevation: 3,
    zIndex: 5,
  },
  likeIcon: {
    width: 20,
    height: 20,
    marginRight: 8,
    zIndex: 10,
  },
  likeText: {
    fontSize: 14,
    fontWeight: '500',
    color: '#59695C',
    fontFamily: 'DM Mono',
  },
  typeInputWrapper: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#224229',
    backgroundColor: '#f9f9f9',
    marginBottom: 10,
  },
  typeInput: {
    flex: 1,
    height: '100%',
    fontSize: 14,
    textAlignVertical: 'center',
    padding: 0,
  },
});
